FROM python:3.11-slim
WORKDIR /app

COPY api/requirements.txt /app/
RUN pip install --no-cache-dir -r api/requirements.txt

COPY api /app
COPY model /app/model
COPY config /app/config

ENV PYTHONUNBUFFERED=1
WORKDIR /app
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "-Q", "retrain"]
